"""add payment id to audit logs

Revision ID: 0d43f4cf08a5
Revises: c1318fc87349
Create Date: 2026-08-30 10:57:53.003704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d43f4cf08a5'
down_revision: Union[str, Sequence[str], None] = 'c1318fc87349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_index('ix_audit_logs_event_created', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_payment_created', 'audit_logs', ['payment_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_payment_id'), 'audit_logs', ['payment_id'], unique=False)
    op.alter_column('orders', 'payment_required',
               existing_type=sa.BOOLEAN(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('orders', 'payment_approved',
               existing_type=sa.BOOLEAN(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('orders', 'payment_approved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('orders', 'payment_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_payment_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_payment_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_created', table_name='audit_logs')
    op.drop_column('audit_logs', 'payment_id')
    # ### end Alembic commands ###
