"""add payment foreign key to audit logs

Revision ID: 479709cc26f0
Revises: 0d43f4cf08a5
Create Date: 2026-08-30 11:37:27.203160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479709cc26f0'
down_revision: Union[str, Sequence[str], None] = '0d43f4cf08a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_logs', 'payments', ['payment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###
