"""add idempotency keys

Revision ID: 6c19d20d03c1
Revises: e86d7e5fbcfb
Create Date: 2026-08-31 10:53:39.213095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c19d20d03c1'
down_revision: Union[str, Sequence[str], None] = 'e86d7e5fbcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('operation', sa.String(length=50), nullable=False))
    op.add_column('idempotency_keys', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('idempotency_keys', sa.Column('response_status_code', sa.Integer(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('idempotency_keys', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_idempotency_merchant_key'), 'idempotency_keys', type_='unique')
    op.create_index(op.f('ix_idempotency_keys_operation'), 'idempotency_keys', ['operation'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_resource_id'), 'idempotency_keys', ['resource_id'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_resource_type'), 'idempotency_keys', ['resource_type'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_status'), 'idempotency_keys', ['status'], unique=False)
    op.create_unique_constraint('uq_idempotency_merchant_operation_key', 'idempotency_keys', ['merchant_id', 'operation', 'key'])
    op.create_foreign_key(None, 'idempotency_keys', 'merchants', ['merchant_id'], ['id'])
    op.drop_column('idempotency_keys', 'status_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'idempotency_keys', type_='foreignkey')
    op.drop_constraint('uq_idempotency_merchant_operation_key', 'idempotency_keys', type_='unique')
    op.drop_index(op.f('ix_idempotency_keys_status'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_resource_type'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_resource_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_operation'), table_name='idempotency_keys')
    op.create_unique_constraint(op.f('uq_idempotency_merchant_key'), 'idempotency_keys', ['merchant_id', 'key'], postgresql_nulls_not_distinct=False)
    op.alter_column('idempotency_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('idempotency_keys', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('idempotency_keys', 'updated_at')
    op.drop_column('idempotency_keys', 'error_message')
    op.drop_column('idempotency_keys', 'response_status_code')
    op.drop_column('idempotency_keys', 'status')
    op.drop_column('idempotency_keys', 'operation')
    # ### end Alembic commands ###
