"""add payment method details

Revision ID: 979c2a356821
Revises: 954542e53dcf
Create Date: 2026-08-31 12:14:04.683055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979c2a356821'
down_revision: Union[str, Sequence[str], None] = '954542e53dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method_details', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_payments_payment_method'), 'payments', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_method'), table_name='payments')
    op.drop_column('payments', 'payment_method_details')
    # ### end Alembic commands ###
