"""add idempotency keys

Revision ID: e86d7e5fbcfb
Revises: 30265b8540d0
Create Date: 2026-08-31 10:33:49.931298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86d7e5fbcfb'
down_revision: Union[str, Sequence[str], None] = '30265b8540d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_merchant_event_created'), table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_merchant_event_created'), 'audit_logs', ['merchant_id', 'event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###
